import Head from 'next/head';
import Header from '../components/Header';
import Dashboard from '../components/Dashboard/Dashboard';
import DailyOverview from '../components/Overview/DailyOverview';
import { Box } from '@chakra-ui/layout';

export default function Home() {
    return (
        <Box>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Header />
            <Dashboard />
            <DailyOverview />
        </Box>
    );
}
